### ISSUE TITLE
Typo on "Hosting on Github Pages Tutorial"

### ISSUE THREAD

**Issue by ZaykaNya** [material-docs/material-docs-documentation#20]
**Describe the bug**
Typo in word "ну"

**To Reproduce**
1. Go to 'Hosting on Github Pages'
2. Scroll down to 'Решение на практике'
3. See error 'ну'

**Expected behavior**
I was expected to see 'не'.

**Screenshots**
![image](https://user-images.githubusercontent.com/48089558/95927027-64289900-0dc6-11eb-9cf2-dc806b6c0b61.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser Google Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS13.7
 - Browser Safari

**Additional context**
I hope you will fix this huge bug soon.

**Comment by DanilAndreev** [comment]
Thank you for you bug report. We will fix this in next versions.
